# Generated by Django 3.2.7 on 2021-12-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('danceability', models.FloatField(default=0.0)),
                ('energy', models.FloatField(default=0.0)),
                ('key', models.IntegerField(default=0)),
                ('loudness', models.FloatField(default=0.0)),
                ('mode', models.IntegerField(default=0)),
                ('speechness', models.FloatField(default=0.0)),
                ('acousticness', models.FloatField(default=0.0)),
                ('instrumentalness', models.FloatField(default=0.0)),
                ('liveness', models.FloatField(default=0.0)),
                ('valence', models.FloatField(default=0.0)),
                ('tempo', models.FloatField(default=0.0)),
                ('type', models.CharField(default='', max_length=50)),
                ('id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('uri', models.CharField(default='', max_length=100)),
                ('ref_track', models.URLField(default='')),
                ('url_features', models.URLField(default='')),
                ('duration', models.IntegerField(default=0)),
                ('time_signature', models.IntegerField(default=0)),
                ('genre', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
