# Generated by Django 3.2.7 on 2021-12-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vibeland_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.FloatField(default=0.0),
        ),
    ]
