# Generated by Django 3.2.7 on 2021-12-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vibeland_api', '0002_alter_song_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mode',
            field=models.FloatField(default=0.0),
        ),
    ]
