# Generated by Django 3.2.7 on 2021-12-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vibeland_api', '0003_alter_song_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='trackid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
