# Generated by Django 3.2.7 on 2021-12-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vibeland_api', '0004_auto_20211203_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='centroid',
            field=models.IntegerField(default=0),
        ),
    ]
