# Generated by Django 3.2.7 on 2021-12-15 23:05

from django.db import migrations, models
import stream_django.activity


class Migration(migrations.Migration):

    dependencies = [
        ('Vibeland_api', '0005_song_centroid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist_name', models.CharField(default='', max_length=100)),
                ('song_name', models.CharField(default='', max_length=100)),
            ],
            bases=(models.Model, stream_django.activity.Activity),
        ),
    ]
